.SUFFIXES: .cpp
include ./conf.mk

#comment this for verbose make
MAKEFLAGS+= -s
#uncomment this if you want to know about Compiler extension
# CPPFLAGS += -pedantic


#for sgi   -- comment out the lines below to use on HP
#CC=CC -g0 -o32
#CC=gcc

# Compiler options
OPTS+=-g
OPTS+=-O0
#OPTS+=-O2
OPTS+=-DDEBUG=1

UNAME = $(shell uname)

ifeq ($(UNAME), Linux)
CXX       = g++
CPPFLAGS += $(OPTS) -Wall
endif


#######################################




GLUI_TOOLS = GENERATED/bin/ppm2array

.PHONY: all setup examples tools clean depend doc doc-pdf doc-dist dist tests

all: $(GLUI_LIB) examples tools



# DO NOT DELETE THIS LINE -- make depend depends on it.
